### PR TITLE
Do not provide default implementation for SystemOfUnitsService.getPrefix

### PR DESCRIPTION
**Pull request by desruisseaux**
Interface `SystemOfUnitsService` provides a default implementation for `getPrefixes(Class)` method, but that default assumes an implementation based on `java.lang.Enum`. Default methods in Unit-API interfaces should work without making any assumption on implementation choices. If knowledge or assumptions about details is required, then we should let implementors provide this method.

---
This change is [Reviewable](https://reviewable.io/reviews/unitsofmeasurement/unit-api/107)

### CODE REVIEW

**Comment by keilw** [comment]
@andi-huber @otaviojava @dautelle What do you think about that? It makes little sense to force something into the RI when implementing enum types are now in the API. The default method can be overridden where necessary but it make sense here because he enums are in the API.

**Comment by keilw** [comment]
While the restriction to `getPrefixes(Class<? extends Prefix> prefixType)` would be tempting, it won't compile with Maven in Java 9.0.4:

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/werner/git/unit-api/src/test/java/javax/measure/spi/TestSystemOfUnitsService.java:[68,37] incompatible types: inference variable E has incompatible bounds
    equality constraints: capture#1 of ? extends U
    upper bounds: javax.measure.Prefix,java.lang.Enum<E>
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.737 s
[INFO] Finished at: 2018-08-02T01:54:57+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:testCompile (default-testCompile) on project unit-api: Compilation failure
[ERROR] /C:/Users/werner/git/unit-api/src/test/java/javax/measure/spi/TestSystemOfUnitsService.java:[68,37] incompatible types: inference variable E has incompatible bounds
[ERROR]     equality constraints: capture#1 of ? extends U
[ERROR]     upper bounds: javax.measure.Prefix,java.lang.Enum<E>
[ERROR] -> [Help 1]
[ERROR]

**Comment by andi-huber** [comment]
I agree with Werner, there is nothing that prevents implementations to override the `default`. And having a `default` implementation in the API does not strike me as a disadvantage.

Cheers!

**Comment by desruisseaux** [comment]
What do you mean by "the enum type is now in the API"? The `Prefix` that I see [on master](https://github.com/unitsofmeasurement/unit-api/blob/master/src/main/java/javax/measure/Prefix.java) is still an interface. Did I missed something?

Of course user can override the default, but my argument is that the default should work with any implementation, otherwise it is implementation-specific and should be provided by the implementor.

**Comment by desruisseaux** [comment]
So we agree that the use of `Enum` is currently not part of the API, and consequently that the default `getPrefixes(Class)` method is currently implementation-specific?

Alternatives that I see are:

* Let `getPrefix(Class)` implementation to implementors;
* Or if you really want a default implementation, specify in the API that `Prefix` must be an `Enum` (but I don't see what would be the benefit of this restriction other than keeping this default method).

**Comment by keilw** [comment]
No, that's a misconception, both [BinaryPrefix](https://github.com/unitsofmeasurement/unit-api/blob/master/src/main/java/javax/measure/BinaryPrefix.java) and [MetricPrefix](https://github.com/unitsofmeasurement/unit-api/blob/master/src/main/java/javax/measure/MetricPrefix.java) use `Enum` here. This has been a kind of "hybrid enum" @dautelle already introduced in a preliminary version of JScience (after 4). Those types were in thr RI and SE implementation but thanks to @andi-huber the two most common prefixes are now here in the API. Hence a matching default algorithm to support them should also be here, not in the RI.

**Comment by desruisseaux** [comment]
Okay, I missed that the API provides two `Prefix` implementations. I will change the pull request later into something that mention that in the javadoc.

**Comment by keilw** [comment]
Great, thanks. Is it ok to close this one because it also won't merge automatically any more.
